CREATE TABLE [CommCRM].[E_ACCOUNT_TERR_LOADER]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[OWNERID] [nvarchar](18) NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[ACCOUNT_VOD__C] [nvarchar](18) NULL,
	[EXTERNAL_ID_VOD__C] [nvarchar](50) NULL,
	[TERRITORY_VOD__C] [nvarchar](max) NULL,
	[MOBILE_ID_VOD__C] [nvarchar](100) NULL,
	[TERRITORY_TO_ADD_VOD__C] [nvarchar](255) NULL,
	[TERRITORY_TO_DROP_VOD__C] [nvarchar](255) NULL,
	[ELA_MANUAL_TERRITORY__C] [nvarchar](max) NULL,
	[ELA_TERRITORY_CHUNK_1__C] [nvarchar](255) NULL,
	[ELA_TERRITORY_CHUNK_2__C] [nvarchar](255) NULL,
	[ELA_TERRITORY_CHUNK_3__C] [nvarchar](255) NULL,
	[ELA_TERRITORY_CHUNK_4__C] [nvarchar](255) NULL,
	[ELA_TERRITORY_CHUNK_5__C] [nvarchar](255) NULL,
	[ELA_TERRITORY_CHUNK_6__C] [nvarchar](255) NULL,
	[ELA_MANUAL_TERR_TO_ADD__C] [nvarchar](255) NULL,
	[ELA_MANUAL_TERR_TO_DROP__C] [nvarchar](255) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)