CREATE TABLE [CommCRM].[E_ACCOUNT_PLAN]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[RECORDTYPEID] [nvarchar](18) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[LASTACTIVITYDATE] [date] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[LASTVIEWEDDATE] [datetime] NULL,
	[LASTREFERENCEDDATE] [datetime] NULL,
	[STRENGTHS__C] [nvarchar](max) NULL,
	[WEAKNESSES__C] [nvarchar](max) NULL,
	[OPPORTUNITIES__C] [nvarchar](max) NULL,
	[THREATS__C] [nvarchar](max) NULL,
	[ACCOUNT_VOD__C] [nvarchar](18) NULL,
	[TYPE__C] [nvarchar](1000) NULL,
	[DESCRIPTION_VOD__C] [nvarchar](max) NULL,
	[STATUS__C] [nvarchar](1000) NULL,
	[ACTIVE_VOD__C] [bit] NULL,
	[MOBILE_ID_VOD__C] [nvarchar](100) NULL,
	[PERCENT_COMPLETE_VOD__C] [nvarchar](100) NULL,
	[ELA_ACCPLAN_ACTION_ID__C] [nvarchar](40) NULL,
	[ELA_DUE_DATE__C] [date] NULL,
	[ELA_BUDGET__C] [numeric](18, 0) NULL,
	[ELA_FORECAST__C] [numeric](18, 0) NULL,
	[ELA_POTENTIAL__C] [numeric](18, 0) NULL,
	[HEALTH_VOD__C] [nvarchar](1000) NULL,
	[ELA_PLAN_BRANDS__C] [nvarchar](max) NULL,
	[ELA_CUMULATIVE_ASK__C] [nvarchar](max) NULL,
	[ELA_SAM_MILESTONE__C] [nvarchar](1000) NULL,
	[ELA_ACTIVE_VALUE_DRIVER__C] [nvarchar](4000) NULL,
	[ELA_TOOLS__C] [nvarchar](4000) NULL,
	[ELA_ASK_1__C] [nvarchar](max) NULL,
	[ELA_ASK_2__C] [nvarchar](max) NULL,
	[ELA_ASK_3__C] [nvarchar](max) NULL,
	[ELA_FIT_1__C] [nvarchar](max) NULL,
	[ELA_FIT_2__C] [nvarchar](max) NULL,
	[ELA_FIT_3__C] [nvarchar](max) NULL,
	[ELA_VALUE_TRACKING_1__C] [nvarchar](max) NULL,
	[ELA_VALUE_TRACKING_2__C] [nvarchar](max) NULL,
	[ELA_VALUE_TRACKING_3__C] [nvarchar](max) NULL,
	[ELA_TARGET_INFLUENCERS_1__C] [nvarchar](max) NULL,
	[ELA_TARGET_INFLUENCERS_2__C] [nvarchar](max) NULL,
	[ELA_TARGET_INFLUENCERS_3__C] [nvarchar](max) NULL,
	[ELA_SAM_PLAN__C] [nvarchar](1000) NULL,
	[PRE_ESTABLISHED_VALUE_1_USD__C] [nvarchar](100) NULL,
	[PRE_ESTABLISHED_VALUE_2_USD__C] [nvarchar](100) NULL,
	[PRE_ESTABLISHED_VALUE_3_USD__C] [nvarchar](100) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)