CREATE TABLE [CommCRM].[E_ADDRESS]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[RECORDTYPEID] [nvarchar](18) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[LASTVIEWEDDATE] [datetime] NULL,
	[LASTREFERENCEDDATE] [datetime] NULL,
	[ACCOUNT_VOD__C] [nvarchar](18) NULL,
	[ADDRESS_LINE_2_VOD__C] [nvarchar](100) NULL,
	[CITY_VOD__C] [nvarchar](50) NULL,
	[EXTERNAL_ID_VOD__C] [nvarchar](120) NULL,
	[DEA_VOD__C] [nvarchar](9) NULL,
	[DEA_EXPIRATION_DATE_VOD__C] [date] NULL,
	[DEA_LICENSE_ADDRESS_VOD__C] [nvarchar](max) NULL,
	[PHONE_VOD__C] [nvarchar](40) NULL,
	[FAX_VOD__C] [nvarchar](40) NULL,
	[COMMENT_VOD__C] [nvarchar](255) NULL,
	[SHIPPING_VOD__C] [bit] NULL,
	[PRIMARY_VOD__C] [bit] NULL,
	[LICENSE_VOD__C] [nvarchar](25) NULL,
	[LICENSE_EXPIRATION_DATE_VOD__C] [date] NULL,
	[STAFF_NOTES_VOD__C] [nvarchar](max) NULL,
	[APPT_REQUIRED_VOD__C] [bit] NULL,
	[OFFICE_NOTES_VOD__C] [nvarchar](max) NULL,
	[LICENSE_STATUS_VOD__C] [nvarchar](1000) NULL,
	[ZIP_4_VOD__C] [nvarchar](4) NULL,
	[PHONE_2_VOD__C] [nvarchar](40) NULL,
	[FAX_2_VOD__C] [nvarchar](40) NULL,
	[INCLUDE_IN_TERRITORY_ASSIGNMENT_VOD__C] [bit] NULL,
	[MOBILE_ID_VOD__C] [nvarchar](100) NULL,
	[INACTIVE_VOD__C] [bit] NULL,
	[LOCK_VOD__C] [bit] NULL,
	[COUNTRY_VOD__C] [nvarchar](1000) NULL,
	[LATITUDE_VOD__C] [numeric](18, 0) NULL,
	[ZIP_VOD__C] [nvarchar](20) NULL,
	[BEST_TIMES_VOD__C] [nvarchar](max) NULL,
	[SOURCE_VOD__C] [nvarchar](1000) NULL,
	[BRICK_VOD__C] [nvarchar](80) NULL,
	[ASSMCA_VOD__C] [nvarchar](100) NULL,
	[DEA_ADDRESS_VOD__C] [bit] NULL,
	[DEA_SCHEDULE_VOD__C] [nvarchar](100) NULL,
	[BUSINESS_VOD__C] [bit] NULL,
	[BILLING_VOD__C] [bit] NULL,
	[HOME_VOD__C] [bit] NULL,
	[MAILING_VOD__C] [bit] NULL,
	[STATE_VOD__C] [nvarchar](1000) NULL,
	[LONGITUDE_VOD__C] [numeric](18, 0) NULL,
	[DEA_STATUS_VOD__C] [nvarchar](1000) NULL,
	[ENTITY_REFERENCE_ID_VOD__C] [nvarchar](20) NULL,
	[CONTROLLING_ADDRESS_VOD__C] [nvarchar](18) NULL,
	[CONTROLLED_ADDRESS_VOD__C] [bit] NULL,
	[NO_ADDRESS_COPY_VOD__C] [bit] NULL,
	[SAMPLE_SEND_STATUS_VOD__C] [nvarchar](1000) NULL,
	[PHYSICAL__C] [bit] NULL,
	[ELA_ADDRESS_TYPE__C] [nvarchar](1000) NULL,
	[ELA_REGION__C] [nvarchar](100) NULL,
	[ELA_ADDR_COUNTY__C] [nvarchar](50) NULL,
	[ELA_STATE_PROVINCE__C] [nvarchar](18) NULL,
	[ELA_TAX_JURISDICTION__C] [nvarchar](20) NULL,
	[ELA_SAP_ID__C] [nvarchar](50) NULL,
	[ELA_FIPS_CODE__C] [nvarchar](10) NULL,
	[ELA_CO_OR_ATTN__C] [nvarchar](40) NULL,
	[ELA_SHP_INSTRCTNS__C] [nvarchar](120) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)