CREATE TABLE [CommCRM].[E_CALL2_SAMPLE]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[LASTACTIVITYDATE] [date] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[LASTVIEWEDDATE] [datetime] NULL,
	[LASTREFERENCEDDATE] [datetime] NULL,
	[ACCOUNT_VOD__C] [nvarchar](18) NULL,
	[CALL_DATE_VOD__C] [date] NULL,
	[QUANTITY_VOD__C] [numeric](18, 0) NULL,
	[LOT_VOD__C] [nvarchar](80) NULL,
	[MOBILE_ID_VOD__C] [nvarchar](100) NULL,
	[CALL2_VOD__C] [nvarchar](18) NULL,
	[PRODUCT_VOD__C] [nvarchar](18) NULL,
	[OVERRIDE_LOCK_VOD__C] [bit] NULL,
	[DISTRIBUTOR_VOD__C] [nvarchar](255) NULL,
	[ATTENDEE_TYPE_VOD__C] [nvarchar](1000) NULL,
	[ENTITY_REFERENCE_ID_VOD__C] [nvarchar](100) NULL,
	[DELIVERY_STATUS_VOD__C] [nvarchar](1000) NULL,
	[APPLY_LIMIT_VOD__C] [bit] NULL,
	[LIMIT_APPLIED_VOD__C] [bit] NULL,
	[MANUFACTURER_VOD__C] [nvarchar](255) NULL,
	[AMOUNT_VOD__C] [nvarchar](100) NULL,
	[PRODUCT_VALUE_VOD__C] [nvarchar](100) NULL,
	[CUSTOM_TEXT_VOD__C] [nvarchar](80) NULL,
	[TAG_ALERT_NUMBER_VOD__C] [nvarchar](20) NULL,
	[ELA_EXPIRATION_DATE__C] [date] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)