CREATE TABLE [CommCRM].[E_CASE]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[ISDELETED] [bit] NULL,
	[CASENUMBER] [nvarchar](30) NULL,
	[CONTACTID] [nvarchar](18) NULL,
	[ACCOUNTID] [nvarchar](18) NULL,
	[ASSETID] [nvarchar](18) NULL,
	[PARENTID] [nvarchar](18) NULL,
	[SUPPLIEDNAME] [nvarchar](80) NULL,
	[SUPPLIEDEMAIL] [nvarchar](80) NULL,
	[SUPPLIEDPHONE] [nvarchar](40) NULL,
	[SUPPLIEDCOMPANY] [nvarchar](80) NULL,
	[TYPE] [nvarchar](1000) NULL,
	[RECORDTYPEID] [nvarchar](18) NULL,
	[STATUS] [nvarchar](1000) NULL,
	[REASON] [nvarchar](1000) NULL,
	[ORIGIN] [nvarchar](1000) NULL,
	[SUBJECT] [nvarchar](255) NULL,
	[PRIORITY] [nvarchar](1000) NULL,
	[DESCRIPTION] [nvarchar](max) NULL,
	[ISCLOSED] [bit] NULL,
	[CLOSEDDATE] [datetime] NULL,
	[ISESCALATED] [bit] NULL,
	[HASCOMMENTSUNREADBYOWNER] [bit] NULL,
	[HASSELFSERVICECOMMENTS] [bit] NULL,
	[OWNERID] [nvarchar](18) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[CONTACTPHONE] [nvarchar](40) NULL,
	[CONTACTMOBILE] [nvarchar](40) NULL,
	[CONTACTEMAIL] [nvarchar](80) NULL,
	[CONTACTFAX] [nvarchar](40) NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[LASTVIEWEDDATE] [datetime] NULL,
	[LASTREFERENCEDDATE] [datetime] NULL,
	[ELA_DATE_CLOSED__C] [datetime] NULL,
	[ELA_DATE_OPENED__C] [datetime] NULL,
	[ELA_EXTERNAL_ID__C] [nvarchar](255) NULL,
	[ELA_FOLLOW_UP_DATE__C] [date] NULL,
	[ELA_LAST_PAID_DATE__C] [date] NULL,
	[ELA_ORDER__C] [nvarchar](18) NULL,
	[ELA_SUB_TYPE__C] [nvarchar](1000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)