CREATE TABLE [CommCRM].[E_CLM_PRESENTATION]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[OWNERID] [nvarchar](18) NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[LASTVIEWEDDATE] [datetime] NULL,
	[LASTREFERENCEDDATE] [datetime] NULL,
	[MOBILE_ID_VOD__C] [nvarchar](100) NULL,
	[PRESENTATION_ID_VOD__C] [nvarchar](100) NULL,
	[PRODUCT_VOD__C] [nvarchar](18) NULL,
	[DEFAULT_PRESENTATION_VOD__C] [bit] NULL,
	[TRAINING_VOD__C] [bit] NULL,
	[PARENTID_VOD__C] [nvarchar](100) NULL,
	[HIDDEN_VOD__C] [bit] NULL,
	[TYPE_VOD__C] [nvarchar](1000) NULL,
	[APPROVED_VOD__C] [bit] NULL,
	[COPIED_FROM_VOD__C] [nvarchar](20) NULL,
	[COPY_DATE_VOD__C] [datetime] NULL,
	[DIRECTORY_VOD__C] [nvarchar](18) NULL,
	[ORIGINAL_RECORD_ID_VOD__C] [nvarchar](20) NULL,
	[END_DATE_VOD__C] [date] NULL,
	[ELA_COUNTRY__C] [nvarchar](4000) NULL,
	[ELA_DISEASE_TOPIC__C] [nvarchar](4000) NULL,
	[ELA_LANGUAGE__C] [nvarchar](1000) NULL,
	[ELA_PROMOTIONAL_PIECE_ID__C] [nvarchar](50) NULL,
	[ELA_SPECIES__C] [nvarchar](4000) NULL,
	[SURVEY_VOD__C] [nvarchar](18) NULL,
	[START_DATE_VOD__C] [date] NULL,
	[STATUS_VOD__C] [nvarchar](1000) NULL,
	[VEXTERNAL_ID_VOD__C] [nvarchar](255) NULL,
	[VAULT_DNS_VOD__C] [nvarchar](255) NULL,
	[VAULT_DOC_ID_VOD__C] [nvarchar](100) NULL,
	[VAULT_EXTERNAL_ID_VOD__C] [nvarchar](255) NULL,
	[VAULT_GUID_VOD__C] [nvarchar](255) NULL,
	[VAULT_LAST_MODIFIED_DATE_TIME_VOD__C] [datetime] NULL,
	[VERSION_VOD__C] [nvarchar](100) NULL,
	[ENABLE_SURVEY_OVERLAY_VOD__C] [bit] NULL,
	[CONTROL_VISIBILITY_VOD__C] [nvarchar](1000) NULL,
	[DESCRIPTION_VOD__C] [nvarchar](max) NULL,
	[KEYWORDS_VOD__C] [nvarchar](255) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)