CREATE TABLE [CommCRM].[E_CONSENT_TYPE]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[RECORDTYPEID] [nvarchar](18) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[LASTVIEWEDDATE] [datetime] NULL,
	[LASTREFERENCEDDATE] [datetime] NULL,
	[CONSENT_HEADER_VOD__C] [nvarchar](18) NULL,
	[CHANNEL_LABEL_VOD__C] [nvarchar](100) NULL,
	[CHANNEL_SOURCE_VOD__C] [nvarchar](max) NULL,
	[CONSENT_EXPIRES_IN_VOD__C] [nvarchar](1000) NULL,
	[DEFAULT_CONSENT_TYPE_VOD__C] [nvarchar](1000) NULL,
	[DISCLAIMER_TEXT_VOD__C] [nvarchar](max) NULL,
	[DISPLAY_ORDER_VOD__C] [numeric](18, 0) NULL,
	[PRODUCT_PREFERENCE_VOD__C] [nvarchar](1000) NULL,
	[ZVOD_CONSENT_DEFAULT_CONSENT_TEXT_VOD__C] [nvarchar](max) NULL,
	[ZVOD_CONSENT_LINE_VOD__C] [bit] NULL,
	[ZVOD_SIGNATURE_CAPTURE_VOD__C] [bit] NULL,
	[DOUBLE_OPT_IN_VOD__C] [bit] NULL,
	[ZVOD_CONSENT_ACTIVITY_TRACKING_VOD__C] [nvarchar](max) NULL,
	[ELA_EXTERNAL_ID__C] [nvarchar](255) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)