CREATE TABLE [CommCRM].[E_DEAL]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[LASTVIEWEDDATE] [datetime] NULL,
	[LASTREFERENCEDDATE] [datetime] NULL,
	[ELA_ACCOUNT__C] [nvarchar](18) NULL,
	[ELA_DEAL_DEFINITION__C] [nvarchar](18) NULL,
	[ELA_ACTUALS_LYTD_CURRENCY__C] [numeric](18, 0) NULL,
	[ELA_ACTUALS_LYTD_NUMBER__C] [numeric](18, 0) NULL,
	[ELA_ACTUALS_LAST_YEAR_CURRENCY__C] [numeric](18, 0) NULL,
	[ELA_ACTUALS_LAST_YEAR_NUMBER__C] [numeric](18, 0) NULL,
	[ELA_ACTUALS_TO_DATE_CURRENCY__C] [numeric](18, 0) NULL,
	[ELA_ACTUALS_TO_DATE_NUMBER__C] [numeric](18, 0) NULL,
	[ELA_CLOSED__C] [bit] NULL,
	[ELA_COMMITTEDAMT__C] [numeric](18, 0) NULL,
	[ELA_COMMITTEDQTY__C] [numeric](18, 0) NULL,
	[ELA_DEAL_DETAILS__C] [nvarchar](max) NULL,
	[ELA_EXTERNAL_ID__C] [nvarchar](80) NULL,
	[ELA_MULTI_CLIENT__C] [bit] NULL,
	[ELA_ORDER_NUMBER__C] [nvarchar](20) NULL,
	[ELA_PERCENT_DISCOUNT__C] [nvarchar](100) NULL,
	[ELA_PERIOD__C] [nvarchar](255) NULL,
	[ELA_REFDATE__C] [date] NULL,
	[ELA_SIGNATURE_DATE__C] [date] NULL,
	[ELA_SUBSCRIBED__C] [bit] NULL,
	[ELA_PRICE__C] [numeric](18, 0) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)