CREATE TABLE [CommCRM].[E_GROUP]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[NAME] [nvarchar](40) NULL,
	[DEVELOPERNAME] [nvarchar](80) NULL,
	[RELATEDID] [nvarchar](18) NULL,
	[TYPE] [nvarchar](1000) NULL,
	[EMAIL] [nvarchar](80) NULL,
	[OWNERID] [nvarchar](18) NULL,
	[DOESSENDEMAILTOMEMBERS] [bit] NULL,
	[DOESINCLUDEBOSSES] [bit] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)