CREATE TABLE [CommCRM].[E_INVENTORY_MONITORING]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[ACCOUNT_VOD__C] [nvarchar](18) NULL,
	[DATETIME_VOD__C] [datetime] NULL,
	[ENTITY_REFERENCE_ID_VOD__C] [nvarchar](100) NULL,
	[LOCK_VOD__C] [bit] NULL,
	[MOBILE_CREATED_DATETIME_VOD__C] [datetime] NULL,
	[MOBILE_ID_VOD__C] [nvarchar](100) NULL,
	[MOBILE_LAST_MODIFIED_DATETIME_VOD__C] [datetime] NULL,
	[NOTES_VOD__C] [nvarchar](max) NULL,
	[STATUS_VOD__C] [nvarchar](1000) NULL,
	[CALL2_VOD__C] [nvarchar](18) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)