CREATE TABLE [CommCRM].[E_INVENTORY_ORDER]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[OWNERID] [nvarchar](18) NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[LASTVIEWEDDATE] [datetime] NULL,
	[LASTREFERENCEDDATE] [datetime] NULL,
	[APPROVED_VOD__C] [bit] NULL,
	[APPROVED_BY_VOD__C] [nvarchar](100) NULL,
	[APPROVED_DATE_VOD__C] [date] NULL,
	[APPROVER_USER_ID_VOD__C] [nvarchar](18) NULL,
	[EXTERNAL_ID_VOD__C] [nvarchar](100) NULL,
	[ORDER_CREATE_DATE_VOD__C] [date] NULL,
	[ORDER_FOR_USER_VOD__C] [nvarchar](18) NULL,
	[ORDER_STATUS_VOD__C] [nvarchar](1000) NULL,
	[REQUIRE_APPROVAL_VOD__C] [bit] NULL,
	[UNLOCK_VOD__C] [bit] NULL,
	[ORDER_SUBMIT_DATE_VOD__C] [date] NULL,
	[ORDER_TYPE_VOD__C] [nvarchar](1000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)