CREATE TABLE [CommCRM].[E_INVENTORY_ORDER_LINE]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[LASTVIEWEDDATE] [datetime] NULL,
	[LASTREFERENCEDDATE] [datetime] NULL,
	[INVENTORY_ORDER_ALLOCATION_VOD__C] [nvarchar](18) NULL,
	[INVENTORY_ORDER_HEADER_VOD__C] [nvarchar](18) NULL,
	[EXCEPTION_COMMENTS_VOD__C] [nvarchar](255) NULL,
	[EXCEPTION_SEVERITY_VOD__C] [nvarchar](1000) NULL,
	[EXCEPTION_TYPE_VOD__C] [nvarchar](1000) NULL,
	[INVENTORY_ORDER_LINE_STATUS_VOD__C] [nvarchar](1000) NULL,
	[ORDER_FULFILLED_QUANTITY_VOD__C] [numeric](18, 0) NULL,
	[ORDER_QUANTITY_VOD__C] [numeric](18, 0) NULL,
	[ORDER_QUANTITY_UOM_VOD__C] [nvarchar](1000) NULL,
	[PRODUCT_VOD__C] [nvarchar](18) NULL,
	[REQUESTED_DELIVERY_DATE_VOD__C] [date] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)