CREATE TABLE [CommCRM].[E_MULTICHANNEL_ACTIVITY]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[OWNERID] [nvarchar](18) NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[RECORDTYPEID] [nvarchar](18) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[ACCOUNT_EXTERNAL_ID_MAP_VOD__C] [nvarchar](18) NULL,
	[ACCOUNT_VOD__C] [nvarchar](18) NULL,
	[CALL_VOD__C] [nvarchar](18) NULL,
	[CITY_VOD__C] [nvarchar](20) NULL,
	[CLIENT_NAME_VOD__C] [nvarchar](20) NULL,
	[CLIENT_OS_VOD__C] [nvarchar](20) NULL,
	[CLIENT_TYPE_VOD__C] [nvarchar](20) NULL,
	[COUNTRY_VOD__C] [nvarchar](20) NULL,
	[DEBUG_VOD__C] [bit] NULL,
	[DEVICE_VOD__C] [nvarchar](20) NULL,
	[IP_ADDRESS_VOD__C] [nvarchar](32) NULL,
	[MULTICHANNEL_ACTIVITY_VOD__C] [nvarchar](18) NULL,
	[REFERRING_SITE_VOD__C] [nvarchar](255) NULL,
	[REGION_VOD__C] [nvarchar](20) NULL,
	[SENT_EMAIL_VOD__C] [nvarchar](18) NULL,
	[SESSION_ID_VOD__C] [nvarchar](50) NULL,
	[SITE_VOD__C] [nvarchar](18) NULL,
	[START_DATETIME_VOD__C] [datetime] NULL,
	[TOTAL_DURATION_VOD__C] [numeric](18, 0) NULL,
	[URL_VOD__C] [nvarchar](255) NULL,
	[USER_AGENT_VOD__C] [nvarchar](255) NULL,
	[VEXTERNAL_ID_VOD__C] [nvarchar](255) NULL,
	[VIEWPORT_HEIGHT_VOD__C] [numeric](18, 0) NULL,
	[VIEWPORT_WIDTH_VOD__C] [numeric](18, 0) NULL,
	[ORGANIZER_VOD__C] [nvarchar](18) NULL,
	[TERRITORY_VOD__C] [nvarchar](100) NULL,
	[CLM_LOCATION_LATITUDE_VOD__C] [numeric](18, 0) NULL,
	[CLM_LOCATION_LONGITUDE_VOD__C] [numeric](18, 0) NULL,
	[CLM_LOCATION_SERVICES_STATUS_VOD__C] [nvarchar](1000) NULL,
	[MEDIA_PREVIEW_VOD__C] [bit] NULL,
	[MOBILE_ID_VOD__C] [nvarchar](100) NULL,
	[TRAINING_VOD__C] [bit] NULL,
	[SAVED_FOR_LATER_VOD__C] [bit] NULL,
	[EVENT_ATTENDEE_VOD__C] [nvarchar](18) NULL,
	[MEDICAL_EVENT_VOD__C] [nvarchar](18) NULL,
	[PRODUCT_VOD__C] [nvarchar](18) NULL,
	[COLOR_VOD__C] [nvarchar](1000) NULL,
	[ICON_VOD__C] [nvarchar](1000) NULL,
	[MCD_PRIMARY_KEY_VOD__C] [nvarchar](255) NULL,
	[RECORD_TYPE_NAME_VOD__C] [nvarchar](80) NULL,
	[DETAIL_GROUP_VOD__C] [nvarchar](18) NULL,
	[EM_EVENT_VOD__C] [nvarchar](18) NULL,
	[SENT_MESSAGE_EXTERNAL_ID_VOD__C] [nvarchar](255) NULL,
	[SENT_MESSAGE_VOD__C] [nvarchar](18) NULL,
	[ELA_ACTIVITY_DESCRIPTION__C] [nvarchar](max) NULL,
	[ELA_EXTERNAL_SYSTEM__C] [nvarchar](255) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)