CREATE TABLE [CommCRM].[E_ORDER_REL_SNAPSHOT]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[ELA_ORDER__C] [nvarchar](18) NULL,
	[CREDIT_RISK_CODE__C] [nvarchar](50) NULL,
	[ELA_CREDIT_LIMIT__C] [numeric](18, 0) NULL,
	[ELA_CREDIT_OPEN_SALES_VALUE__C] [numeric](18, 0) NULL,
	[ELA_CREDIT_TOTAL_OVER_30__C] [numeric](18, 0) NULL,
	[ELA_CREDIT_TOTAL_RECEIVABLE__C] [numeric](18, 0) NULL,
	[ELA_EXTERNAL_ID__C] [nvarchar](255) NULL,
	[ELA_ORDER_VALUE_AT_RELEASE__C] [numeric](18, 0) NULL,
	[ELA_RELEASED_BY__C] [nvarchar](18) NULL,
	[ELA_RELEASED_DATE_TIME__C] [datetime] NULL,
	[ELA_SNAPSHOT_TYPE__C] [nvarchar](1000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)