CREATE TABLE [CommCRM].[E_ORDER_LINE]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[RECORDTYPEID] [nvarchar](18) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[ORDER_VOD__C] [nvarchar](18) NULL,
	[LIST_AMOUNT_VOD__C] [nvarchar](100) NULL,
	[MOBILE_ID_VOD__C] [nvarchar](100) NULL,
	[NET_AMOUNT_VOD__C] [nvarchar](100) NULL,
	[PRODUCT_VOD__C] [nvarchar](18) NULL,
	[QUANTITY_VOD__C] [numeric](18, 0) NULL,
	[RULE_VOD__C] [nvarchar](max) NULL,
	[U_M_VOD__C] [nvarchar](100) NULL,
	[LINE_WARNING_VOD__C] [nvarchar](255) NULL,
	[BRAND_WARNING_VOD__C] [nvarchar](255) NULL,
	[GROUP_WARNING_VOD__C] [nvarchar](255) NULL,
	[LINE_DISCOUNT_RULE_VOD__C] [nvarchar](100) NULL,
	[LINE_DISCOUNT_VOD__C] [nvarchar](100) NULL,
	[NET_PRICE_RULE_VOD__C] [nvarchar](100) NULL,
	[NET_PRICE_VOD__C] [nvarchar](100) NULL,
	[TOTAL_DISCOUNT_VOD__C] [nvarchar](100) NULL,
	[TOTAL_DISCOUNT_RULE_VOD__C] [nvarchar](100) NULL,
	[BRAND_DISCOUNT_RULE_VOD__C] [nvarchar](100) NULL,
	[GROUP_DISCOUNT_RULE_VOD__C] [nvarchar](100) NULL,
	[ORDER_DISCOUNT_RULE_VOD__C] [nvarchar](100) NULL,
	[FREE_GOODS_VOD__C] [numeric](18, 0) NULL,
	[FREE_GOODS_RULE_VOD__C] [numeric](18, 0) NULL,
	[LIST_PRICE_RULE_VOD__C] [nvarchar](100) NULL,
	[ORDER_DISCOUNT_VOD__C] [nvarchar](100) NULL,
	[OVERRIDE_LOCK_VOD__C] [bit] NULL,
	[PRODUCT_IDENTIFIER_VOD__C] [nvarchar](80) NULL,
	[DISCOUNT_CALCULATION_PATH_VOD__C] [numeric](18, 0) NULL,
	[ELA_NOTES__C] [nvarchar](255) NULL,
	[ELA_BASE_PRICE__C] [nvarchar](100) NULL,
	[ELA_BILLABLE__C] [bit] NULL,
	[ELA_CHARGED_DOSES__C] [numeric](18, 0) NULL,
	[ELA_COUNTY_TAX__C] [nvarchar](100) NULL,
	[ELA_DISCOUNT_INCENTIVE__C] [nvarchar](100) NULL,
	[ELA_DISCOUNT_OTHER__C] [nvarchar](100) NULL,
	[ELA_EXTERNAL_ID__C] [nvarchar](255) NULL,
	[ELA_LINE_NUMBER__C] [nvarchar](6) NULL,
	[ELA_LOT_NUMBERS__C] [nvarchar](4000) NULL,
	[ELA_MARKETING_PROGRAM__C] [nvarchar](1000) NULL,
	[ELA_NET_PRICE__C] [nvarchar](100) NULL,
	[ELA_QTY_SHIPPED__C] [numeric](18, 0) NULL,
	[ELA_SAMPLED_DOSES__C] [numeric](18, 0) NULL,
	[ELA_SHIPPED_DATE__C] [date] NULL,
	[ELA_SPECIAL_TAX__C] [nvarchar](100) NULL,
	[ELA_STATE_TAX__C] [nvarchar](100) NULL,
	[ELA_STATUS__C] [nvarchar](1000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)