CREATE TABLE [CommCRM].[E_PUB_ACCNT_LIST]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[OWNERID] [nvarchar](18) NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[LASTVIEWEDDATE] [datetime] NULL,
	[LASTREFERENCEDDATE] [datetime] NULL,
	[ELA_ACTIVE__C] [bit] NULL,
	[ELA_DESCRIPTION__C] [nvarchar](max) NULL,
	[ELA_DIVISIONS__C] [nvarchar](4000) NULL,
	[ELA_END_DATE__C] [date] NULL,
	[ELA_EXTERNAL_ID__C] [nvarchar](100) NULL,
	[ELA_START_DATE__C] [date] NULL,
	[ELA_TYPE__C] [nvarchar](1000) NULL,
	[ELA_OPEN_ENROLLMENT_END_DATE__C] [date] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)