CREATE TABLE [CommCRM].[E_PUB_ACCNT_LIST_MEMBER]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[ELA_ACCOUNT__C] [nvarchar](18) NULL,
	[ELA_EXTERNAL_ID__C] [nvarchar](100) NULL,
	[MOBILE_ID_VOD__C] [nvarchar](100) NULL,
	[ELA_PUB_ACCT_LIST__C] [nvarchar](18) NULL,
	[ELA_MEMBER_ID__C] [nvarchar](50) NULL,
	[RECORDTYPEID] [nvarchar](18) NULL,
	[ELA_COMMENTS__C] [nvarchar](max) NULL,
	[ELA_DONT_SUBMIT_APPROVAL_REQ__C] [bit] NULL,
	[ELA_MEMBERSHIP_END_DATE__C] [date] NULL,
	[ELA_NEW_MEMBERSHIP_START_DATE__C] [date] NULL,
	[ELA_STATUS__C] [nvarchar](1000) NULL,
	[ELA_MEMBERSHIP_START_DATE__C] [date] NULL,
	[ELA_NEW_MEMBERSHIP_END_DATE__C] [date] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)