CREATE TABLE [CommCRM].[E_RECORDTYPE]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[NAME] [nvarchar](80) NULL,
	[DEVELOPERNAME] [nvarchar](80) NULL,
	[NAMESPACEPREFIX] [nvarchar](15) NULL,
	[DESCRIPTION] [nvarchar](255) NULL,
	[BUSINESSPROCESSID] [nvarchar](18) NULL,
	[SOBJECTTYPE] [nvarchar](1000) NULL,
	[ISACTIVE] [bit] NULL,
	[ISPERSONTYPE] [bit] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[CREATEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[SYSTEMMODSTAMP] [datetime] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)