CREATE TABLE [CommCRM].[E_RETAIL_PROD_INFO]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[RECORDTYPEID] [nvarchar](18) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[ELA_ACCOUNT__C] [nvarchar](18) NULL,
	[ELA_EXTERNAL_ID__C] [nvarchar](255) NULL,
	[ELA_FIRST_SHIP_DATE__C] [date] NULL,
	[ELA_INIT_PROD_PACK_SND_DT__C] [date] NULL,
	[ELA_LAST_SHIP_DATE__C] [date] NULL,
	[ELA_NEW_CUSTOMER_DATE__C] [date] NULL,
	[ELA_NEW_CUSTOMER__C] [bit] NULL,
	[ELA_NEXT_SHIP_DATE__C] [date] NULL,
	[ELA_ON_INCENTIVE__C] [bit] NULL,
	[ELA_PACKAGE_SIZE_PREF__C] [nvarchar](1000) NULL,
	[ELA_PREFERRED_SHIP_METHOD__C] [nvarchar](1000) NULL,
	[ELA_PURCHASING_STATUS__C] [nvarchar](1000) NULL,
	[ELA_SCHED_DOSES_PER_SHIP_AL__C] [numeric](18, 0) NULL,
	[ELA_SCHED_DOSES_PER_SHIP__C] [numeric](18, 0) NULL,
	[ELA_SCHED_END_DATE__C] [date] NULL,
	[ELA_SCHED_FIRST_SHIP_DATE__C] [date] NULL,
	[ELA_SCHED_INTERVAL_TYPE__C] [nvarchar](1000) NULL,
	[ELA_SCHED_ORDER_CHANGE_RSN__C] [nvarchar](1000) NULL,
	[ELA_SCHED_SHIP_INTERVAL__C] [numeric](18, 0) NULL,
	[ELA_SCHED_TYPE__C] [nvarchar](1000) NULL,
	[ELA_TAX_EX_CERT_EFF_DT__C] [date] NULL,
	[ELA_TAX_EXEMPT__C] [bit] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)