CREATE TABLE [CommCRM].[E_SAMPLE_INVENTORY]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[OWNERID] [nvarchar](18) NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[LASTVIEWEDDATE] [datetime] NULL,
	[LASTREFERENCEDDATE] [datetime] NULL,
	[INVENTORY_FOR_VOD__C] [nvarchar](18) NULL,
	[STATUS_VOD__C] [nvarchar](1000) NULL,
	[AUDIT_VOD__C] [bit] NULL,
	[INVENTORY_TYPE_VOD__C] [nvarchar](1000) NULL,
	[INVENTORY_FROM_DATE_VOD__C] [datetime] NULL,
	[UNLOCK_VOD__C] [bit] NULL,
	[SUBMITTED_VOD__C] [bit] NULL,
	[SUBMITTED_DATE_VOD__C] [datetime] NULL,
	[NO_SAMPLE_LOTS_VOD__C] [bit] NULL,
	[PREVIOUS_INVENTORY_DATE_TIME_VOD__C] [datetime] NULL,
	[INVENTORY_DATE_TIME_VOD__C] [datetime] NULL,
	[MOBILE_ID_VOD__C] [nvarchar](100) NULL,
	[MOBILE_CREATED_DATETIME_VOD__C] [datetime] NULL,
	[MOBILE_LAST_MODIFIED_DATETIME_VOD__C] [datetime] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)