CREATE TABLE [CommCRM].[E_SALES_PRODUCT_SUMMARY]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[OWNERID] [nvarchar](18) NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[RECORDTYPEID] [nvarchar](18) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[LASTVIEWEDDATE] [datetime] NULL,
	[LASTREFERENCEDDATE] [datetime] NULL,
	[ELA_DISPLAY_ACCOUNT__C] [nvarchar](18) NULL,
	[ELA_AVG_ORDER_VALUE__C] [numeric](18, 0) NULL,
	[ELA_AVG_TIME_BTW_ORDERS__C] [numeric](18, 0) NULL,
	[ELA_CY_M_01_Q__C] [numeric](18, 0) NULL,
	[ELA_CY_M_01__C] [numeric](18, 0) NULL,
	[ELA_CY_M_02_Q__C] [numeric](18, 0) NULL,
	[ELA_CY_M_02__C] [numeric](18, 0) NULL,
	[ELA_CY_M_03_Q__C] [numeric](18, 0) NULL,
	[ELA_CY_M_03__C] [numeric](18, 0) NULL,
	[ELA_CY_M_04_Q__C] [numeric](18, 0) NULL,
	[ELA_CY_M_04__C] [numeric](18, 0) NULL,
	[ELA_CY_M_05_Q__C] [numeric](18, 0) NULL,
	[ELA_CY_M_05__C] [numeric](18, 0) NULL,
	[ELA_CY_M_06_Q__C] [numeric](18, 0) NULL,
	[ELA_CY_M_06__C] [numeric](18, 0) NULL,
	[ELA_CY_M_07_Q__C] [numeric](18, 0) NULL,
	[ELA_CY_M_07__C] [numeric](18, 0) NULL,
	[ELA_CY_M_08_Q__C] [numeric](18, 0) NULL,
	[ELA_CY_M_08__C] [numeric](18, 0) NULL,
	[ELA_CY_M_09_Q__C] [numeric](18, 0) NULL,
	[ELA_CY_M_09__C] [numeric](18, 0) NULL,
	[ELA_CY_M_10_Q__C] [numeric](18, 0) NULL,
	[ELA_CY_M_10__C] [numeric](18, 0) NULL,
	[ELA_CY_M_11_Q__C] [numeric](18, 0) NULL,
	[ELA_CY_M_11__C] [numeric](18, 0) NULL,
	[ELA_CY_M_12_Q__C] [numeric](18, 0) NULL,
	[ELA_CY_M_12__C] [numeric](18, 0) NULL,
	[ELA_FIRST_PURCHASE_DATE__C] [date] NULL,
	[ELA_LY2_AMT__C] [numeric](18, 0) NULL,
	[ELA_LY2_QTY__C] [numeric](18, 0) NULL,
	[ELA_LYTD2_AMT__C] [numeric](18, 0) NULL,
	[ELA_LYTD2_QTY__C] [numeric](18, 0) NULL,
	[ELA_LYTD_AMT__C] [numeric](18, 0) NULL,
	[ELA_LYTD_QTY__C] [numeric](18, 0) NULL,
	[ELA_LY_AMT__C] [numeric](18, 0) NULL,
	[ELA_LY_M_01_Q__C] [numeric](18, 0) NULL,
	[ELA_LY_M_01__C] [numeric](18, 0) NULL,
	[ELA_LY_M_02_Q__C] [numeric](18, 0) NULL,
	[ELA_LY_M_02__C] [numeric](18, 0) NULL,
	[ELA_LY_M_03_Q__C] [numeric](18, 0) NULL,
	[ELA_LY_M_03__C] [numeric](18, 0) NULL,
	[ELA_LY_M_04_Q__C] [numeric](18, 0) NULL,
	[ELA_LY_M_04__C] [numeric](18, 0) NULL,
	[ELA_LY_M_05_Q__C] [numeric](18, 0) NULL,
	[ELA_LY_M_05__C] [numeric](18, 0) NULL,
	[ELA_LY_M_06_Q__C] [numeric](18, 0) NULL,
	[ELA_LY_M_06__C] [numeric](18, 0) NULL,
	[ELA_LY_M_07_Q__C] [numeric](18, 0) NULL,
	[ELA_LY_M_07__C] [numeric](18, 0) NULL,
	[ELA_LY_M_08_Q__C] [numeric](18, 0) NULL,
	[ELA_LY_M_08__C] [numeric](18, 0) NULL,
	[ELA_LY_M_09_Q__C] [numeric](18, 0) NULL,
	[ELA_LY_M_09__C] [numeric](18, 0) NULL,
	[ELA_LY_M_10_Q__C] [numeric](18, 0) NULL,
	[ELA_LY_M_10__C] [numeric](18, 0) NULL,
	[ELA_LY_M_11_Q__C] [numeric](18, 0) NULL,
	[ELA_LY_M_11__C] [numeric](18, 0) NULL,
	[ELA_LY_M_12_Q__C] [numeric](18, 0) NULL,
	[ELA_LY_M_12__C] [numeric](18, 0) NULL,
	[ELA_LY_QTY__C] [numeric](18, 0) NULL,
	[ELA_LAST_PURCHASE_DATE__C] [date] NULL,
	[ELA_OVERDUE_COLOR__C] [nvarchar](1000) NULL,
	[ELA_STDDEV_TIME_BTW_ORDER__C] [numeric](18, 0) NULL,
	[ELA_YTD_AMT__C] [numeric](18, 0) NULL,
	[ELA_YTD_QTY__C] [numeric](18, 0) NULL,
	[ELA_BUSINESS_UNIT__C] [nvarchar](1000) NULL,
	[ELA_PRODUCT__C] [nvarchar](18) NULL,
	[ELA_SALES_CLASS__C] [nvarchar](1000) NULL,
	[ELA_CURRENCY__C] [nvarchar](10) NULL,
	[ELA_EXTERNAL_ID__C] [nvarchar](255) NULL,
	[ELA_SALES_PARENT_SUMMARY__C] [nvarchar](18) NULL,
	[ELA_ACCOUNT__C] [nvarchar](18) NULL,
	[ELA_LAST_12_MONTHS_AMT__C] [numeric](18, 0) NULL,
	[ELA_LAST_12_MONTHS_QTY__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_01_Q__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_01__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_02_Q__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_02__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_03_Q__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_03__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_04_Q__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_04__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_05_Q__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_05__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_06_Q__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_06__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_07_Q__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_07__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_08_Q__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_08__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_09_Q__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_09__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_10_Q__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_10__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_11_Q__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_11__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_12_Q__C] [numeric](18, 0) NULL,
	[ELA_LY2_M_12__C] [numeric](18, 0) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)