CREATE TABLE [CommCRM].[E_SAMPLE_TRANSACTION]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[RECORDTYPEID] [nvarchar](18) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[LASTVIEWEDDATE] [datetime] NULL,
	[LASTREFERENCEDDATE] [datetime] NULL,
	[LOT_VOD__C] [nvarchar](18) NULL,
	[ADJUST_FOR_VOD__C] [nvarchar](18) NULL,
	[TRANSFER_TO_NAME_VOD__C] [nvarchar](255) NULL,
	[SIGNATURE_VOD__C] [nvarchar](max) NULL,
	[RECEIVED_VOD__C] [bit] NULL,
	[SIGNATURE_DATE_VOD__C] [datetime] NULL,
	[TRANSFERRED_FROM_VOD__C] [nvarchar](18) NULL,
	[CALL_NAME_VOD__C] [nvarchar](100) NULL,
	[RECEIPT_COMMENTS_VOD__C] [nvarchar](max) NULL,
	[TRANSFERRED_DATE_VOD__C] [date] NULL,
	[SUBMITTED_DATE_VOD__C] [date] NULL,
	[TRANSFER_TO_VOD__C] [nvarchar](18) NULL,
	[SHIPMENT_ID_VOD__C] [nvarchar](50) NULL,
	[ADDRESS_LINE_1_VOD__C] [nvarchar](80) NULL,
	[ZIP_VOD__C] [nvarchar](6) NULL,
	[STATUS_VOD__C] [nvarchar](1000) NULL,
	[CITY_VOD__C] [nvarchar](40) NULL,
	[ADJUSTED_DATE_VOD__C] [date] NULL,
	[CONFIRMED_QUANTITY_VOD__C] [numeric](18, 0) NULL,
	[U_M_VOD__C] [nvarchar](1000) NULL,
	[DISCLAIMER_VOD__C] [nvarchar](max) NULL,
	[DISBURSED_TO_VOD__C] [nvarchar](max) NULL,
	[REF_TRANSACTION_ID_VOD__C] [nvarchar](18) NULL,
	[COMMENTS_VOD__C] [nvarchar](max) NULL,
	[SAMPLE_VOD__C] [nvarchar](100) NULL,
	[UNLOCK_VOD__C] [bit] NULL,
	[QUANTITY_VOD__C] [numeric](18, 0) NULL,
	[TRANSFERRED_FROM_NAME_VOD__C] [nvarchar](255) NULL,
	[TYPE_VOD__C] [nvarchar](1000) NULL,
	[LOT_NAME_VOD__C] [nvarchar](80) NULL,
	[REASON_VOD__C] [nvarchar](1000) NULL,
	[GROUP_TRANSACTION_ID_VOD__C] [nvarchar](255) NULL,
	[ZVOD_SAMPLE_LINES_VOD__C] [bit] NULL,
	[ADDRESS_LINE_2_VOD__C] [nvarchar](100) NULL,
	[STATE_VOD__C] [nvarchar](1000) NULL,
	[RETURN_TO_VOD__C] [nvarchar](1000) NULL,
	[SAMPLE_CARD_VOD__C] [nvarchar](15) NULL,
	[ASSMCA_VOD__C] [nvarchar](100) NULL,
	[ACCOUNT_VOD__C] [nvarchar](18) NULL,
	[CALL_DATE_VOD__C] [date] NULL,
	[CALL_DATETIME_VOD__C] [datetime] NULL,
	[DEA_EXPIRATION_DATE_VOD__C] [date] NULL,
	[DEA_VOD__C] [nvarchar](9) NULL,
	[SAMPLE_CARD_REASON_VOD__C] [nvarchar](1000) NULL,
	[ZIP_4_VOD__C] [nvarchar](4) NULL,
	[LICENSE_VOD__C] [nvarchar](25) NULL,
	[REQUEST_RECEIPT_VOD__C] [bit] NULL,
	[CREDENTIALS_VOD__C] [nvarchar](255) NULL,
	[SALUTATION_VOD__C] [nvarchar](255) NULL,
	[MANUFACTURER_VOD__C] [nvarchar](255) NULL,
	[DISTRIBUTOR_VOD__C] [nvarchar](255) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)