CREATE TABLE [CommCRM].[E_SUGGESTION_FEEDBACK]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[RECORDTYPEID] [nvarchar](18) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[SUGGESTION_VOD__C] [nvarchar](18) NULL,
	[ACCOUNT_VOD__C] [nvarchar](18) NULL,
	[ACTIVITY_EXECUTION_TYPE_VOD__C] [nvarchar](1000) NULL,
	[CALL2_VOD__C] [nvarchar](18) NULL,
	[CALL_OBJECTIVE_VOD__C] [nvarchar](18) NULL,
	[DISMISSFEEDBACK1_VOD__C] [nvarchar](1000) NULL,
	[DISMISSFEEDBACK2_VOD__C] [nvarchar](1000) NULL,
	[DISMISSFEEDBACK3_VOD__C] [nvarchar](1000) NULL,
	[DISMISSFEEDBACK4_VOD__C] [nvarchar](1000) NULL,
	[MOBILE_ID_VOD__C] [nvarchar](100) NULL,
	[SENT_EMAIL_VOD__C] [nvarchar](18) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)