CREATE TABLE [CommCRM].[E_TERRITORY_HIER]
(
	[ROOT_TERRITORY] [nvarchar](80) NULL,
	[ROOT_TERRITORY_DESC] [nvarchar](1000) NULL,
	[ROOT_TERRITORY_ID] [nvarchar](18) NULL,
	[DESCENDANT_TERRITORY] [nvarchar](80) NULL,
	[DESCENDANT_TERRITORY_DESC] [nvarchar](1000) NULL,
	[DESCENDANT_TERRITORY_ID] [nvarchar](18) NULL,
	[TERRITORY_PATH] [nvarchar](4000) NULL,
	[RELATIVE_LEVEL] [int] NOT NULL,
	[FULL_TERRITORY_PATH] [nvarchar](4000) NULL,
	[FULL_LEVEL] [int] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH ( [ROOT_TERRITORY_ID] ),
	CLUSTERED COLUMNSTORE INDEX
)