CREATE TABLE [CommCRM].[E_TERRITORY]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[NAME] [nvarchar](80) NULL,
	[PARENTTERRITORYID] [nvarchar](18) NULL,
	[DESCRIPTION] [nvarchar](1000) NULL,
	[ACCOUNTACCESSLEVEL] [nvarchar](1000) NULL,
	[OPPORTUNITYACCESSLEVEL] [nvarchar](1000) NULL,
	[CASEACCESSLEVEL] [nvarchar](1000) NULL,
	[CONTACTACCESSLEVEL] [nvarchar](1000) NULL,
	[FORECASTUSERID] [nvarchar](18) NULL,
	[MAYFORECASTMANAGERSHARE] [bit] NULL,
	[RESTRICTOPPORTUNITYTRANSFER] [bit] NULL,
	[DEVELOPERNAME] [nvarchar](80) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MASTER_ALIGN_ID_VOD__C] [nvarchar](36) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)