CREATE TABLE [CommCRM].[E_UNSUBSCRIBE]
(
	[TABLE_ROWID] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](18) NULL,
	[CURRENT_ROW] [int] NULL,
	[START_DATE] [date] NULL,
	[EXPIRED_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](1000) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](1000) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[OWNERID] [nvarchar](18) NULL,
	[ISDELETED] [bit] NULL,
	[NAME] [nvarchar](80) NULL,
	[RECORDTYPEID] [nvarchar](18) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDBYID] [nvarchar](18) NULL,
	[LASTMODIFIEDDATE] [datetime] NULL,
	[LASTMODIFIEDBYID] [nvarchar](18) NULL,
	[SYSTEMMODSTAMP] [datetime] NULL,
	[MAYEDIT] [bit] NULL,
	[ISLOCKED] [bit] NULL,
	[UNSUBSCRIBE_CANCEL_HTML_VOD__C] [nvarchar](max) NULL,
	[UNSUBSCRIBE_CONFIRM_HTML_VOD__C] [nvarchar](max) NULL,
	[UNSUBSCRIBE_HTML_VOD__C] [nvarchar](max) NULL,
	[UNSUBSCRIBE_IDENTIFIER_VOD__C] [nvarchar](255) NULL,
	[UNSUBSCRIBE_MODIFY_CONFIRM_HTML_VOD__C] [nvarchar](max) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[ID] ASC
	)
)