CREATE TABLE [CommCRM].[L_ACCOUNT]
(
	[ID] [nvarchar](18) NULL,
	[EXTERNAL_ID_VOD__C] [nvarchar](120) NULL,
	[ELA_ACCOUNT_NAME_ENGLISH__C] [nvarchar](80) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)