CREATE TABLE [CommCRM].[PROCESS_MONITOR]
(
	[PIPELINE_NAME] [varchar](250) NULL,
	[STORED_PROCEDURE_NAME] [varchar](255) NOT NULL,
	[RUN_DATE] [date] NOT NULL,
	[EXECUTION_TIME] [date] NOT NULL,
	[STATUS] [varchar](20) NOT NULL,
	[MESSAGE] [varchar](8000) NOT NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)