CREATE TABLE [CommCRMConfig].[CFG_TERR_MGMT_BUS_UNIT]
(
	[DIVISION] [varchar](255) NOT NULL,
	[BUSINESS_UNIT] [varchar](80) NOT NULL,
	[AUTO_ALIGN_TYPE] [varchar](80) NOT NULL,
	[SPCL_OWNRSHP_FLG] [varchar](1) NOT NULL,
	[SALESFORCE_FLG] [varchar](1) NOT NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)