CREATE TABLE [CommCRMConfig].[CFG_TERR_MGMT_SPHERE]
(
	[DIVISION] [varchar](255) NOT NULL,
	[BUSINESS_UNIT] [varchar](80) NOT NULL,
	[SPHERE_TYPE] [varchar](80) NOT NULL,
	[ACCOUNT_TYPE] [varchar](80) NOT NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)