CREATE TABLE [CommCRMConfig].[E_ORDER_SEND_LOG]
(
	[ORDER_ID] [nvarchar](18) NULL,
	[EXTRNL_SYS_TYP] [nvarchar](30) NULL,
	[SENT_DATE] [date] NULL,
	[CREATE_DATE] [date] NULL,
	[CREATE_NAME] [nvarchar](30) NULL,
	[LAST_UPDATE_DATE] [date] NULL,
	[LAST_UPDATE_NAME] [nvarchar](30) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)